version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:00"
      timezone: "Europe/Rome"
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "DTrombett"
    open-pull-requests-limit: 10
